---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:
    - name: Create molecule instance(s)
      lxd_container:
        name: "{{ item.name }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org/
          protocol: simplestreams
          alias: "{{ item.image }}"
        devices:
          root:
            path: "/"
            type: "disk"
            pool: "{{ lookup('env', 'LXD_POOL') | default('default', true) }}"
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 6000
      with_items: "{{ molecule_yml.platforms }}"
